SDK-1300: pointers
getyoti/yoti-go-sdk pull request #168
Opened 2020-08-18 09:49 UTC by echarrod

- Use pointers for doc scan structs & receivers
- Don't use pointer for time.Time - from [godocs](https://golang.org/src/time/time.go): 
> Programs using times should typically store and pass them as values, not pointers. That is, time variables and struct fields should be of type time.Time, not *time.Time.

2020-08-18 20:04 UTC, echarrod commented
@lkramer do you know if we can always expect a check/task/media to have a createdDate and lastUpdated date? Just wondering whether we want to have pointers for values like this, where we can have nil if for some reason they are not present

2020-08-19 10:11 UTC, davidgrayston commented
I think it would be safer (less misleading) for dates to be `nil` instead of `0001-01-01T00:00:00Z`, when not present. Other SDKs are `nil/null` in this unlikely situation.

2020-08-19 10:14 UTC, davidgrayston approved these changes
Look good - I'm leaning towards date/times being pointers so that they are `nil` when not available (based on what we have done in other SDKs). If we are certain they will always be present, then it's fine how you have it.

2020-08-19 10:19 UTC, lkramer commented
> @lkramer do you know if we can always expect a check/task/media to have a createdDate and lastUpdated date? Just wondering whether we want to have pointers for values like this, where we can have nil if for some reason they are not present

The "correct" way to check if a time object is 0 is to use IsZero() https://golang.org/pkg/time/#Time.IsZero

2020-08-19 10:22 UTC, davidgrayston requested changes

2020-08-19 10:22 UTC, davidgrayston commented on docscan/session/retrieve/check_response.go
> +	LastUpdated    time.Time         `json:"last_updated"`
We might need to add `omitempty` to properties if they're not always present. I believe we have done this in all other SDKs.

2020-08-19 14:38 UTC, davidgrayston commented on docscan/session/retrieve/check_response.go
> +	LastUpdated    time.Time         `json:"last_updated"`
As discussed `omitempty` isn't necessary when unserializing

2020-08-19 15:09 UTC, echarrod commented
Have gone with using pointers in e75ee06, based on what we have in the other SDKs, and also wanting to be as clear as possible that the value isn't present, rather than it potentially being missed if the time.Time was just the default value

2020-08-19 17:11 UTC, davidgrayston approved these changes

2020-08-19 17:18 UTC, merged